### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by Suzii** [matuskropuch/talkio#1]
# Status: ✔️ 
Below are just suggestions to consider for the next milestones.

I love that you are using Typescript. Your app is very nice - both visually and code-wise, (clean code and well-structured to components). Keep up the good work 👍 
 
# Code suggestions
- Get rid of the warnings in the console.
- `ChannelNameEditor` - why is the render method so complicated? You do not need the `output` variable, just return straight away, the code will be much simpler 😉 
- `key={Math.random()}` is a really, really baaad idea, check out why: https://reactjs.org/docs/lists-and-keys.html

**Comment by matuskropuch** [comment]
Can you please take a look at how I resolved these suggestions in this PR? #2

**Comment by Suzii** [comment]
Yep, looks great 😉 Regarding the React 'key' property: Yes, for the prototype purposes it is okay, as far as you know what it means and why it should not be done. I will mention it on today's lecture as well 😊 Thanks.
