### ISSUE TITLE
Milestone #2

### ISSUE THREAD

**Issue by Suzii** [matuskropuch/talkio#3]
# Status: ✔️ 
Below are just suggestions to consider for the next milestones.

Very nice and clean code, easy to read 😄 

⚠️ Do not forget to implement all the functionality mentioned in the assignement -> inviting users to channels, upvoting/downvoting messages. Login/logout should be there as well -  it is not explicitly mentioned in the assignment, but you kind of expect that in a messaging app you would be able to chat with other people than yourself :)

# Code suggestions
- Consider using `classnames` npm package for use cases such as one in `ChannelListItem:17`
- Some typescript interfaces are still not readonly (`ChannelMessageInput`) - I am not saying it is mandatory, but it helps to prevent bugs ;)
- Consider using `combineReducers` from redux package for your `rootReducer`
- In channels.ts `CHANNEL_RENAME` case, use same pattern - spreading channel object (using object spread operator '…') as you do in `MESSAGE_SEND` - it makes the code more extendable
- In `ChannelMessageInput.tsx` -> you have to set button `type="submit"` if you want to be able to submit whole form (`onSubmit`) by clicking on the button. In Chrome right now, message can only be submitted by pressing Enter, while clicking on a button does nothing.
- I suggest you have a look at the API that you need to integrate your project with and adjust your redux state and models accordingly (have same properties for Message, Channel models as the API returns). For example, I don't think it will be necessary to sort messages by timestamp because the API will return them already sorted as far as I know. Moreover, it might be a good idea to nest the messages collection into the channel object (it is 1-n relationship, so the nesting should be okay as one message will always belong to exactly one channel).

**Comment by matuskropuch** [comment]
Thank you for your comments, especially the ones about store design. I tried hard to come up with as flat design as possible but your insights are very good. I will address all your comments in upcoming commits and will make a pull request. Will you please then take a look at it again? Thanks again 😊

**Comment by Suzii** [comment]
Sure thing 😊 As for the messages - they can be normalized, of course, but in my opinion it is perfectly okay to nest them within channel they belong to. It should be easier to work with 😊

**Comment by matuskropuch** [comment]
I addressed your feedback in this PR #4 can you please have a look at it? Thank you very much 😊

**Comment by Suzii** [comment]
Sorry, for the delay, I am kind of snowed under work right now. I will have a look at the code during the weekend, if that's okay 😉

**Comment by matuskropuch** [comment]
That’s perfectly alright. I really appreciate your time spent on reviewing this. 😊

**Comment by matuskropuch** [comment]
resolved in PR #4
